(setq my-c++-compiler-program "c++")

(defun my-c++-mode-hook()
  (set (make-local-variable 'my-compile-command) "make")
  (my-programming-common-hook)
  (c-toggle-auto-newline)
  (c-set-style "cc-mode")
  (yas/minor-mode 't)
  )
(add-hook 'c++-mode-hook 'my-c++-mode-hook)
(add-hook 'c-mode-hook 'my-c++-mode-hook)
